# Generated by Django 6.0.5 on 2026-05-05 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bmdc_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='chamber_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degrees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degrees_bn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='designation_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name_bn',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='training_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='training_details_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='visiting_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Drop', 'Drop'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Other', 'Other')], default='Tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='dose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='instruction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='food_instruction',
            field=models.CharField(blank=True, choices=[('Before Food', 'Before Food'), ('After Food', 'After Food')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='times_per_day',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
