# Generated by Django 6.0.5 on 2026-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctorprofile_bmdc_no_doctorprofile_chamber_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
